### ISSUE TITLE
zawa has failed to load correctly

### ISSUE THREAD

**Issue by gurgachad** [ZAWA-Evolved/ZAWA#65]
happens every time i launch the game

![Screenshot 2024-10-28 004421](https://github.com/user-attachments/assets/f03757a7-6bd2-45a4-82c0-e92ccd48e252)

log:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/28/24 12:28 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8356/1388477779.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8068/271588719.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$483/1845137754.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD zawa --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/OnDatapackSyncEvent
		at org.zawamod.zawa.Zawa.<init>(Zawa.java:100) ~[?:1.16.5-1.1.0-IntelligentAnimals3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3124/590720754.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3215/455464597.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: zawa-1.16.5-1.1.0-IntelligentAnimals3.jar
	Failure message: ZAWA: Evolved (zawa) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/OnDatapackSyncEvent
	Mod Version: 1.16.5-1.1.0-IntelligentAnimals3
	Mod Issue URL: https://github.com/ZAWA-Evolved/ZAWA/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.OnDatapackSyncEvent
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at org.zawamod.zawa.Zawa.<init>(Zawa.java:100) ~[?:1.16.5-1.1.0-IntelligentAnimals3] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3124/590720754.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3215/455464597.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 606787480 bytes (578 MB) / 1929379840 bytes (1840 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 20
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.15.1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		mcw-bridges-3.0.1-mc1.16.5forge.jar               |Macaw's Bridges               |mcwbridges                    |3.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		zawa-1.16.5-1.1.0-IntelligentAnimals3.jar         |ZAWA: Evolved                 |zawa                          |1.16.5-1.1.0-Intelli|ERROR     |Manifest: NOSIGNATURE
		Blur-1.1.0-1.jar                                  |Blur                          |blur                          |1.1.0-1             |CREATE_REG|Manifest: NOSIGNATURE
		TRansliterationLib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |CREATE_REG|Manifest: NOSIGNATURE
		spiderstpo-1.16.4-2.0.0.jar                       |Spiders 2.0                   |spiderstpo                    |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |CREATE_REG|Manifest: NOSIGNATURE
		FirstPersonMod-2.0.1.jar                          |FirstPersonModel Mod          |firstpersonmod                |2.0.1               |CREATE_REG|Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.3-mc1.16.5forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.3               |CREATE_REG|Manifest: NOSIGNATURE
		mcw-fences-1.1.2-mc1.16.5forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.134.jar                          |Just Enough Items             |jei                           |7.7.1.134           |CREATE_REG|Manifest: NOSIGNATURE
		cavesandcliffs-1.16.5-7.1.4.jar                   |Caves and Cliffs Backport     |cavesandcliffs                |1.16.5-7.1.4        |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.4.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |CREATE_REG|Manifest: NOSIGNATURE
		mcw-windows-2.3.0-mc1.16.5forge.jar               |Macaw's Windows               |mcwwindows                    |2.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |CREATE_REG|Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|Manifest: NOSIGNATURE
		mcwfurnituresbop-1.16.5-1.4.jar                   |Macaw's Furnitures - BOP      |mcwfurnituresbop              |1.16.5-1.4          |CREATE_REG|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |CREATE_REG|Manifest: NOSIGNATURE
		mcwfencesbop-1.16.5-1.5.jar                       |Macaw's Fences - BOP          |mcwfencesbop                  |1.16.5-1.5          |CREATE_REG|Manifest: NOSIGNATURE
		AppleTreesRev-Forge-1.16.5-v2.6.jar               |Apple Trees Revived           |appletreesrev                 |2.6                 |CREATE_REG|Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |CREATE_REG|Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |CREATE_REG|Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.51.jar               |Traveler's Backpack           |travelersbackpack             |5.4.51              |CREATE_REG|Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.3.0.jar                   |Storage Drawers               |storagedrawers                |8.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		blockcarpentry-1.16-0.4.0.jar                     |BlockCarpentry                |blockcarpentry                |1.16-0.4.0          |CREATE_REG|Manifest: NOSIGNATURE
		harvest-1.16.3-1.0.3.jar                          |Harvest                       |harvest                       |1.0.3               |CREATE_REG|Manifest: NOSIGNATURE
		structurize-0.13.219-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.219-ALPHA      |CREATE_REG|Manifest: NOSIGNATURE
		macawsbridgesbop-1.16.5-2.0.jar                   |Macaw's Bridges - Biomes O' Pl|macawsbridgesbop              |1.16.5-2.0          |CREATE_REG|Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.196.jar                  |U Team Core                   |uteamcore                     |3.2.1.196           |CREATE_REG|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		cavebiomeapi-1.16.5-1.4.2.jar                     |CaveBiomeAPI                  |cavebiomeapi                  |1.16.5-1.4.2        |CREATE_REG|Manifest: NOSIGNATURE
		mcw-roofs-2.3.1-mc1.16.5forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.3.1               |CREATE_REG|Manifest: NOSIGNATURE
		mcw-doors-1.1.1forge-mc1.16.5.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		Chisel-MC1.16.5-2.0.1-alpha.4.jar                 |Chisel                        |chisel                        |MC1.16.5-2.0.1-alpha|CREATE_REG|Manifest: NOSIGNATURE
		mcw-furniture-3.3.0-mc1.16.5forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		autoplant-1.16.5-1.0.0.jar                        |autoplant                     |autoplant                     |1.16.5-1.0.0        |CREATE_REG|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |CREATE_REG|Manifest: NOSIGNATURE
		ItemPhysic_v1.4.18_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		cloth-config-4.12.41-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.12.41             |CREATE_REG|Manifest: NOSIGNATURE
		PuzzlesLib-v1.0.15-1.16.5-Forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |CREATE_REG|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		macawsroofsbop-1.16.5-1.9.jar                     |Macaw's Roofs - BOP           |macawsroofsbop                |1.16.5-1.9          |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |CREATE_REG|Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta25.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta25|CREATE_REG|Manifest: NOSIGNATURE
		DynamicTreesBOP-1.16.5-2.0.6.jar                  |Dynamic Trees for Biomes o' Pl|dtbop                         |1.16.5-2.0.6        |CREATE_REG|Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |CREATE_REG|Manifest: NOSIGNATURE
		BetterFoliage-2.7.1-Forge-1.16.5.jar              |Better Foliage                |betterfoliage                 |2.7.1               |CREATE_REG|Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: cc79358f-f536-4576-af12-fea2f1e1b2b3
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.29+Extreme-VL.zip
	OpenGlVersion: 4.6.0 Compatibility Profile Context 24.9.1.240926
	OpenGlRenderer: AMD Radeon RX 6800
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 20

forge: 36.2.0
minecraft: 1.16.5
zawa: 1.1.0

**Comment by gurgachad** [comment]
I'm probably just dumb and it's an easy fix, but I have no idea

I doubt it's a compatibility problem with other mods also I don't have many installed it is a small pack I'm playing on

**Comment by gurgachad** [comment]
nvm im dumb my forge version was a little out of date
